---
comment:
  image:
    repository: batcake/comment
    tag: logging
  service:
    externalPort: 9292
    internalPort: 9292

post:
  image:
    repository: chromko/post
    tag:  latest
  service:
    externalPort: 5000
    internalPort: 5000
  databaseHost:

ui:
  image:
    repository: batcake
    tag:  logging

  postHost:
  postPort:
  commentHost:
  commentPort:

  service:
    externalPort: 9292
