---
comment:
  image:
    repository: batcake/comment
    tag: logging
  service:
    externalPort: 9292
    internalPort: 9292

post:
  image:
    repository: batcake/post
    tag:  latest
  service:
    externalPort: 5000
    internalPort: 5000

ui:
  image:
    repository: batcake
    tag:  logging
  service:
    externalPort: 9292