---
- name: run docker container
  hosts: all
  tasks:
    - name: build container
      command:  docker build -t reddit:latest . 
    - name: build and run docker container  
      docker_container:
        name: reddit
        image: reddit:latest
        published_ports: 9292:9292
        restart_policy: always

