global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#evgeny_nikitin'

