---
- name: Install docker-engine
  hosts: all
  become: true
  vars:
    prerequisites: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
  tasks:
    - name: add apt-key
      command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - name:    Install prerequisites
      apt:     
        name: "{{ prerequisites }}"
        update_cache: yes

    - name:    Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
   
    - name:    Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: add deb repo
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    
    - name: install docker docker-compose docker-ce
      apt: 
        pkg: ['docker-engine', 'docker-compose']
        state: installed
        update_cache: true
   
    - name: install pip
      apt:
        name: python-pip
        state: installed

    - name: enable docker-service
      systemd:
        name: docker
        enabled: yes

    - name: add appuser in docker group
      user:
        append: yes
        name: appuser
        groups: docker
    
    - name: Install pip docker for module docker_container
      pip:
        name: docker


    
