version: '3.3'
services:
  ui:
    volumes:
      - ${PROJECT_PATH}/ui:/app
    command: ["puma", "--debug", "-w", "2"]
  comment:
    volumes:
      - ${PROJECT_PATH}/comment:/app
    command: ["puma", "--debug", "-w", "2"]
  post:
    volumes:
      - ${PROJECT_PATH}/post-py:/app
