version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USER_NAME}/ui:${UI_V}
    ports:
      - ${HOST_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_V}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_V}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
