version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    image: ${USER_NAME}/ui:${UI_V}
    ports:
      - ${HOST_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${USER_NAME}/post:${POST_V}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USER_NAME}/comment:${COMMENT_V}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USER_NAME}/prometheus:2.1
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net


  node-exporter-mongo:
    image: ${USER_NAME}/mongod_exporter:1.0
    command:
    - '-mongodb.uri=mongodb://post_db:27017'
    networks:
      - back_net
  
  cloudprober:
    image: ${USER_NAME}/cloudprober:1.0
    networks: 
      - back_net
      - front_net
    ports:
     - '9313:9313'
      

volumes:
  prometheus_data:
  post_db:

networks:
  front_net:
  back_net:
