groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: Reddit have too big response time
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le)) > 0.1
      for: 1m
      labels:
        severity: page
      annotations:
        description: 'reddit has exceeded threshold(0.1) for the reponse time for 95 percentile'
        summary: '95 percentile threshold exceeded for ui'   